log:
  logDir: ./.logs/
  mainLog: main-%Y-%m-%d.log
  errorLog: error-%Y-%m-%d.log

# ------------------------------------------------------------------------------------------------
mysql:
  host: luvx
  port: 53306
  username: root
  password: 1121
  dbname: boot

redis:
  host: redis-16127.c294.ap-northeast-1-2.ec2.cloud.redislabs.com:16127
  username: default
  password: xx
  timeout: 200
  maxActive: 30
  maxIdle: 30

mongodb:
  uri: mongodb+srv://xxx:xxx@cluster0.r8xxd.mongodb.net
  database: boot
  remote:
    uri: mongodb+srv://xxx:xxx@cluster0.r8xxd.mongodb.net

turso:
  dbname: xxx
  token: xxx

server:
  port: ":8090"
  debug: true

# ------------------------------------------------------------------------------------------------

switch:
  a: true

webclient:
  header:
    weibo:
      referer: https://weibo.com/mygroups?gid=xxx
    bili:
      referer: https://bilibili.com/

keeplive:
  vercel:
    type: redis
    host: xxx
    username: default
    password: xxx
  upstash:
    type: redis
    host: xxx
    username: default
    password: xxx

docker:
  rss:
    rsshub: https://rsshub.umzzz.com
    images: buildpack-deps:latest,golang:latest